repos:
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black
      language_version: python3.12
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.5
  hooks:
    - id: ruff
      args: [--fix]