name: 🐛 Bug Report
description: Report a bug to help us improve OpenSuperWhisper
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us understand and reproduce the issue.
        
        **Important**: Security vulnerabilities should be reported privately to security@opensuperwhisper.org

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - "🔴 Critical - Application crashes or data loss"
        - "🟠 High - Major feature broken"
        - "🟡 Medium - Feature partially broken"
        - "🟢 Low - Minor issue or cosmetic"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of OpenSuperWhisper
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: This is not a security vulnerability (report those privately)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        Describe what happened and what you expected to happen.
        Include any error messages you saw.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Start the application with `opensuperwhisper --config ...`
        2. Click on '...'
        3. Enter '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened, including any error messages
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS Ventura or later (13+)
        - macOS Monterey (12)
        - macOS Big Sur or earlier
        - Ubuntu 22.04
        - Ubuntu 20.04
        - Debian 11+
        - RHEL/CentOS/Rocky 8+
        - Arch Linux
        - Other Linux
        - Docker
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: System Architecture
      options:
        - x86_64 / AMD64
        - ARM64 / Apple Silicon
        - ARM32
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: OpenSuperWhisper Version
      description: What version are you using? Run `opensuperwhisper --version`
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install OpenSuperWhisper?
      options:
        - Downloaded release binary
        - Built from source
        - Docker image
        - Package manager (brew, apt, etc.)
        - Install script
        - Other
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      options:
        - Desktop application
        - Web server
        - Docker container
        - Cloud service
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: |
        Please include any error messages or relevant log files.
        You can find logs in the `logs/` directory or by running with `--debug`
      placeholder: |
        ```
        Error messages here...
        Stack traces...
        Debug output...
        ```
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your configuration (remove sensitive data like API keys)
      placeholder: |
        ```json
        {
          "whisper_model": "base",
          "language": "en",
          ...
        }
        ```
      render: json

  - type: textarea
    id: system_info
    attributes:
      label: System Information
      description: |
        Please provide system information:
        - RAM: 
        - CPU: 
        - GPU (if applicable): 
        - Python version (if built from source): 
        - Node.js version (if applicable): 
      placeholder: |
        - RAM: 16GB
        - CPU: Intel i7-9700K
        - GPU: NVIDIA RTX 3070
        - Python: 3.11.5
        - Node.js: 18.17.0

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Recordings
      description: If applicable, add screenshots or recordings to help explain your problem
      placeholder: Drag and drop images here or paste links

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If you found a workaround, please share it here to help others
      placeholder: Describe any temporary solution you've found

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here:
        - Network environment (proxy, firewall, etc.)
        - Related issues or discussions
        - Anything else that might be relevant

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Steps Taken
      description: What have you already tried?
      options:
        - label: Restarted the application
        - label: Reinstalled the application
        - label: Checked file/folder permissions
        - label: Disabled antivirus/firewall temporarily
        - label: Tried with default configuration
        - label: Checked available disk space
        - label: Verified network connectivity
        - label: Ran with debug/verbose mode
        - label: Checked system requirements
        - label: Tested in safe mode/clean environment